---
# PLUGINS
# ==========================================

# Startup
# -------

# Lazy Loading
# ==========================================

# Languages
# ---------
- repo: thecontinium/vim-markdown-composer
  if: empty($VIM_MINIMAL) && executable('cargo')
  on_ft: markdown
  hook_source: |
    let g:markdown_composer_browser = 'open -a Firefox'
    let g:markdown_composer_autostart = 0
  hook_post_update: |
    call dein#util#_notify("Building: " . g:dein#plugin["name"] )
    if has('nvim')
      call system("cargo build --release")
    else
      call system("cargo build --release --no-default-features --features json-rpc")
    endif


# ==========================================
# Commands
# --------
# ==========================================
# Interface
# ---------
# ==========================================
# Completion
# ----------
# Only NeoVim ------------------------------
# ==========================================
# Denite
# ------
# ==========================================
# Operators
# ---------

# ==========================================
# Text objects
# ------------

#  vim: set ts=2 sw=2 tw=80 et :
