
# PLUGINS

# ==========================================
# new to rafi
# ==========================================

# clojure

# - repo: eraserhd/parinfer-rust
#   build: cargo build --release
#   on_ft: clojure

# - repo: eraserhd/parinfer-rust
#   build: cargo build --release
#   rtp: target/release
#   lazy: true

# - repo: harrygallagher4/nvim-parinfer-rust
#   depends: [parinfer-rust, nvim-treesitter]
#   hook_source: lua vim.api.nvim_create_autocmd('VimEnter', { callback = function() require'parinfer'.setup() end})
#   on_event: VimEnter

- repo: windwp/nvim-autopairs
  if: has('nvim-0.5')
  hook_post_source: lua require('local-plugins.autopairs')

- repo: guns/vim-sexp
  on_event: InsertCharPre
  on_ft: clojure
  hook_add: |
    let g:sexp_enable_insert_mode_mappings = 0

- repo: tpope/vim-sexp-mappings-for-regular-people
  on_event: InsertCharPre
  on_ft: clojure
  depends: vim-sexp

- repo: thecontinium/marked-streaming-nvim
  on_ft: markdown
  hook_post_update : |-
    call system(join([fnamemodify(g:python3_host_prog,":p:h"),"pip install -U pyobjc"],"/"))
  hook_source: |
    let g:marked_streaming_events = 'InsertLeave,CursorHold'
    let g:marked_streaming_open_mapping = '<Leader>O'

- repo: tpope/vim-repeat
  on-source: conjure

- repo: clojure-vim/clojure.vim
  on_ft: clojure

- repo: clojure-vim/vim-jack-in
  on_cmd: [Clj, Lein]
- repo: tpope/vim-dispatch
  on_source: vim-jack-in
- repo: radenling/vim-dispatch-neovim
  on_source: vim-dispatch

- repo: Olical/conjure
  on_ft: clojure
  rev: master
  hook_add:  source $VIM_PATH/config/local-plugins/conjure.vim

- repo: tpope/vim-projectionist
  on_ft: clojure
  hook_add: |-
    autocmd User ProjectionistDetect
      \ call projectionist#append(getcwd(),
      \ {
      \   'src/*.clj': {
      \     'alternate': 'test/{}_test.clj',
      \     'type': 'source'
      \   },
      \   'test/*_test.clj': {
      \     'alternate': 'src/{}.clj',
      \     'type': 'test'
      \   },
      \ })

- repo: hrsh7th/nvim-cmp
  if: has('nvim-0.5')
  on_event: VimEnter
  depends: [ nvim-autopairs, vim-vsnip ]
  hook_post_source: lua require('local-plugins.cmp')

- { repo: PaterJason/cmp-conjure, on_source: nvim-cmp, depends: conjure }

# lsp

- repo: maan2003/lsp_lines.nvim
  if: has('nvim-0.7')
  on_source: nvim-lspconfig
  hook_post_source: lua require('local-plugins.lsp_lines')

- repo: j-hui/fidget.nvim
  if: has('nvim-0.7')
  on_source: nvim-lspconfig
  hook_source: lua require('fidget').setup()

# treesitter

- repo: nvim-treesitter/nvim-treesitter
  if: has('nvim-0.7')
  on_event: VimEnter
  on_cmd: [ TSUpdate, TSInstall, TSInstallInfo, TSModuleInfo, TSConfigInfo ]
  hook_post_update: ':TSUpdate'
  hook_source: lua require('local-plugins.treesitter')

- repo: mrjones2014/nvim-ts-rainbow
  on_source: nvim-treesitter

# yanking and pasting

- repo: kkharji/sqlite.lua

- repo: gbprod/yanky.nvim
  on_event: VimEnter
  if: has('nvim-0.7')
  depends: [telescope.nvim, sqlite.lua]
  hook_post_source: lua require('local-plugins.yanky')

- repo: folke/twilight.nvim
  on_source: zen-mode.nvim
  hook_post_source: lua require('twilight').setup()

- repo: chrisbra/csv.vim
  on_ft: csv
  hook_add: let g:csv_default_delim=','

- { repo: vijaymarupudi/nvim-fzf, if: has("nvim-0.5"), lazy: true }

- repo: bakpakin/fennel.vim

- repo: prncss-xyz/neo-tree-zk.nvim
  if: has('nvim-0.7')
  on_cmd: Neotree
  depends: [ zk-nvim, neo-tree.nvim]

- repo: WhoIsSethDaniel/mason-tool-installer.nvim
  if: has('nvim-0.7')
  on_source: nvim-lspconfig
  hook_post_source: lua require('local-plugins.mason-tool-installer')

# python

# seutup edditing of jupyter notebooks with jupytext
# pip install jupytext
- repo: goerz/jupytext.vim

# ues conjure and lsp in code blocks
- repo: AckslD/nvim-FeMaco.lua
  depends: nvim-treesitter
  on_cmd: FeMaco
  on_lua: femaco
  hook_post_source: lua require("femaco").setup()
  # hook_post_source: lua require('local-plugins.femaco')


# ==========================================
# replace from rafi
# ==========================================

- repo: deris/vim-shot-f
  if: 0
- repo: ggandor/leap.nvim
  hook_add: lua require('local-plugins.leap')
  on_map: { nxo: <Plug> }

# ==========================================
# overide from  rafi
# ==========================================

- repo: nvim-neo-tree/neo-tree.nvim
  if: has('nvim-0.7')
  on_cmd: Neotree
  hook_post_source: lua require('local-plugins.neo-tree')

- repo: mickael-menu/zk-nvim
  if: has('nvim-0.6')
  depends: telescope.nvim
  on_ft: markdown
  on_cmd:
    - ZkIndex
    - ZkNew
    - ZkNewFromTitleSelection
    - ZkNewFromContentSelection
    - ZkNotes
    - ZkTags
    - ZkDeletableNotes
  hook_post_source: lua require('local-plugins.zk')

- repo: lambdalisue/gina.vim
  on_cmd: Gina
  on_ft: [ gitcommit, gitrebase ]
  hook_source: source $VIM_PATH/config/local-plugins/gina.vim

- repo: thecontinium/vim-asterisk
  on_map: { nv: <Plug> }
  overwrite: 1

- repo: folke/which-key.nvim
  if: has('nvim-0.5')
  on_cmd: WhichKey
  hook_post_source: lua require('local-plugins.which-key')

- repo: jose-elias-alvarez/null-ls.nvim
  if: has('nvim-0.7')
  on_event: VimEnter
  depends: nvim-lspconfig
  hook_post_source: lua require('local-plugins.null-ls')

- repo: debugloop/telescope-undo.nvim
  if: has('nvim-0.7')
  depends: telescope.nvim
  on_lua: telescope
  hook_post_source: lua require('telescope').load_extension('undo')

# ==========================================
# temp fixes until rafi updates
# ==========================================







